services:
  backend:
    build:
      context: https://github.com/Layiap/snowbazar_online.git#main
      dockerfile: backend/Dockerfile
    container_name: snowbazar-backend
    volumes:
      - skibazar-db:/app/db
    ports:
      - "8001:8000"
    environment:
      - API_KEY_SKIBAZAR=${API_KEY_SKIBAZAR}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - ABSENDER_EMAIL=${ABSENDER_EMAIL}
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/Layiap/snowbazar_online.git#main
      dockerfile: frontend/Dockerfile
    container_name: snowbazar-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
volumes:
  skibazar-db: