services:
  backend:
    build:
      context: https://github.com/Layiap/snowbazar_online.git#main
      dockerfile: backend/Dockerfile
    container_name: snowbazar-backend
    volumes:
      - skibazar-db:/app/voranmeldung.db
    ports:
      - "8001:8000"
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/Layiap/snowbazar_online.git#main
      dockerfile: frontend/Dockerfile
    container_name: snowbazar-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
volumes:
  skibazar-db: